item {
  name: 'pedestrian'
  id: 1
}

item {
  name: ‘passengercar'
  id: 2
}

item {
  name: 'cyclist'
  id: 3
}

item {
  name: 'largevehicle'
  id: 4
}

item {
  name: 'obstacle'
  id: 5
}

item {
  name: 'vehicle'
  id: 6
}

item {
  name: 'dontcare'
  id: 7
}
